var localization = {
  genres: {
    "Action": "Akční",
    "Adventure": "Dobrodružný",
    "Biography": "Životopisný",    
    "Cartoon": "Animovaný",
    "Catastrophic": "Katastrofický",
    "Comedy": "Komedie",
    "Competition": "Soutěžní",    
    "Crimi": "Krimi",
    "Dance": "Taneční",    
    "Documentary": "Dokumentární",
    "Drama": "Drama",
    "Erotic": "Erotický",
    "Experimental": "Experimentální",
    "Fairytale": "Pohádka", 
    "Family": "Rodinný",    
    "Fantasy": "Fantasy",
    "Film-Noir": "Film-Noir",
    "Historical": "Historický",
    "Horror": "Horor",
    "IMAX": "IMAX",    
    "Music": "Hudební",
    "Musical": "Muzikál",
    "Mystery": "Mysteriózní",
    "Narrative": "Povídkový",    
    "Short": "Krátkometrážní",
    "Parable": "Podobenství",
    "Poetic": "Poetický", 
    "Psychological": "Psychologický",    
    "Publicistic": "Publicistický",    
    "Puppet": "Loutkový",
    "Reality Show": "Reality-TV",
    "Road Movie": "Road movie",
    "Romantic": "Romantický",
    "Scifi": "Sci-Fi",
    "Soup Opera": "Telenovela",    
    "Sports": "Sportovní",
    "Talk Show": "Talk-show",
    "Thriller": "Thriller",
    "Wartime": "Válečný",
    "Western": "Western"
  },

  countries: {  
    "Afghanistan": "Afghánistán",
    "Albania": "Albánie",
    "Algeria": "Alžírsko",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antigua a Barbuda",
    "Argentina": "Argentina",
    "Armenia": "Arménie",
    "Australia": "Austrálie",
    "Austria": "Rakousko",
    "Azerbaijan": "Ázerbajdžán",
    "Bahamas": "Bahamy",
    "Bahrain": "Bahrajn",
    "Bangladesh": "Bangladéš",
    "Barbados": "Barbados",
    "Belarus": "Bělorusko",
    "Belgium": "Belgie",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhútán",
    "Bolivia": "Bolívie",
    "Bosnia and Herzegovina": "Bosna a Hercegovina",
    "Botswana": "Botswana",
    "Brazil": "Brazílie",
    "Brunei": "Brunej",
    "Bulgaria": "Bulharsko",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cabo Verde": "Kapverdy",
    "Cambodia": "Kambodža",
    "Cameroon": "Kamerun",
    "Canada": "Kanada",
    "Central African Republic": "Středoafrická republika",
    "Chad": "Čad",
    "Chile": "Čile",
    "China": "Čína",
    "Colombia": "Kolumbie",
    "Comoros": "Komory",
    "Democratic Republic of the Congo": "Demokratická republika Kongo",
    "Republic of the Congo": "Kongo",
    "Costa Rica": "Kostarika",
    "Cote d'Ivoire": "Pobřeží slonoviny",
    "Croatia": "Chorvatsko",
    "Cuba": "Kuba",
    "Cyprus": "Kypr",
    "Czech Republic": "Česko",
    "Denmark": "Dánsko",
    "Djibouti": "Džibutsko",
    "Dominica": "Dominika",
    "Dominican Republic": "Dominikánská republika",
    "Ecuador": "Ekvádor",
    "Egypt": "Egypt",
    "El Salvador": "Salvador",
    "Equatorial Guinea": "Rovníková Guinea",
    "Eritrea": "Eritrea",
    "Estonia": "Estonsko",
    "Ethiopia": "Etiopie",
    "Fiji": "Fidži",
    "Finland": "Finsko",
    "France": "Francie",
    "Gabon": "Gabon",
    "Gambia": "Gambie",
    "Georgia": "Gruzie",
    "Germany": "Německo",
    "Ghana": "Ghana",
    "Greece": "Řecko",
    "Grenada": "Grenada",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissay",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungary": "Maďarsko",
    "Iceland": "Island",
    "India": "Island",
    "Indonesia": "Indonésie",
    "Iran": "Írán",
    "Iraq": "Irák",
    "Ireland": "Irsko",
    "Israel": "Izrael",
    "Italy": "Itálie",
    "Jamaica": "Jamajka",
    "Japan": "Japonsko",
    "Jordan": "Jordánsko",
    "Kazakhstan": "Kazachstán",
    "Kenya": "Keňa",
    "Kiribati": "Kiribati",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuvait",
    "Kyrgyzstan": "Kyrgystán",
    "Laos": "Laos",
    "Latvia": "Litva",
    "Lebanon": "Libanon",
    "Lesotho": "Lesotho",
    "Liberia": "Libérie",
    "Libya": "Libye",
    "Liechtenstein": "Lichtenštejnsko",
    "Lithuania": "Lotyšsko",
    "Luxembourg": "Lucembursko",
    "Macedonia": "Makedonie",
    "Madagascar": "Madagaskar",
    "Malawi": "Malawi",
    "Malaysia": "Malajsie",
    "Maldives": "Maledivy",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marshall Islands": "Marshallovy ostrovy",
    "Mauritania": "Mauritánie",
    "Mauritius": "Mauricius",
    "Mexico": "Mexiko",
    "Micronesia": "Mikronésie",
    "Moldova": "Moldávie",
    "Monaco": "Monako",
    "Mongolia": "Mongolsko",
    "Montenegro": "Černá Hora",
    "Morocco": "Maroko",
    "Mozambique": "Mozambik",
    "Myanmar": "Myanmar",
    "Namibia": "Namíbie",
    "Nauru": "Nauru",
    "Nepal": "Nepál",
    "Netherlands": "Nizozemsko",
    "New Zealand": "Nový Zéland",
    "Nicaragua": "Nikaragua",
    "Niger": "Niger",
    "Nigeria": "Nigérie",
    "North Korea": "Severní Korea",
    "Norway": "Norsko",
    "Oman": "Omán",
    "Pakistan": "Pákistán",
    "Palau": "Palau",
    "Palestine": "Palestina",
    "Panama": "Panama",
    "Papua New Guinea": "Papua-Nová Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Filipíny",
    "Poland": "Polsko",
    "Portugal": "Portugalsko",
    "Qatar": "Katar",
    "Romania": "Rumunsko",
    "Russia": "Rusko",
    "Rwanda": "Rwanda",
    "Saint Kitts and Nevis": "Svatý Kryštof a Nevis",
    "Saint Lucia": "Svatá Lucie",
    "Saint Vincent and the Grenadines": "Svatý Vincenc a Grenadiny",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Svatý Tomáš a Princův ostrov",
    "Saudi Arabia": "Saúdská Arábie",
    "Senegal": "Senegal",
    "Serbia": "Srbsko",
    "Seychelles": "Seychely",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapur",
    "Slovakia": "Slovensko",
    "Slovenia": "Slovinsko",
    "Solomon Islands": "Šalamounovy ostrovy",
    "Somalia": "Somálsko",
    "South Africa": "Jižní Afrika",
    "South Korea": "Jižní Korea",
    "South Sudan": "Jižní Súdán",
    "Spain": "Španělsko",
    "Sri Lanka": "Srí Lanka",
    "Sudan": "Súdán",
    "Suriname": "Surinam",
    "Swaziland": "Svazijsko",
    "Sweden": "Švédsko",
    "Switzerland": "Švýcarsko",
    "Syria": "Sýrie",
    "Taiwan": "Tchaj-wan",
    "Tajikistan": "Tádžikistán",
    "Tanzania": "Tanzánie",
    "Thailand": "Thajsko",
    "Timor-Leste": "Východní Timor",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad a Tobago",
    "Tunisia": "Tunisko",
    "Turkey": "Turecko",
    "Turkmenistan": "Turkmenistán",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ukraine": "Ukrajina",
    "United Arab Emirates": "Spojené Arabské Emiráty",
    "United Kingdom": "Velká Británie",
    "USA": "USA",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistán",
    "Vanuatu": "Vanuatu",
    "Vatican City": "Vatikán",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Yemen": "Jemen",
    "Zambia": "Zambie",
    "Zimbabwe": "Zimbabwe"
  }
};